name: Pre-Release
on: 
  workflow_call:
   
jobs:
  Pre-Release:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check-out Templates
        run: echo checking out templates!!
        
      - name: Pre-Release Task
        run: echo updating Version Repo!!
        
      - name: Set Release Version
        run: echo setting release version!!
        
      - name: Pre-Build
        run: echo Executing Pre build steps!!
        
      - name: Build and Security Test
        run: echo Build and security testing!!
        
      - name: Build and Sonar Analysis
        run: echo Starting Build+Sonar!!
