name: Pre-Release
on: 
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
    outputs:
      currentversion:
        description: "The version"
        value: ${{ jobs.Pre-Release.outputs.versn }}    
env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
jobs:
  Pre-Release:
    
    runs-on: ubuntu-latest
    outputs:
      versn: ${{ steps.versnid.outputs.versn }}
    steps:
      - uses: actions/checkout@v2
        
      - id: versnid
        run: |
          echo setting release version!!
          aws s3 cp s3://instidbucket1/version1/versionnew.cfg ${{ github.workspace }}/versions.cfg --region us-west-1  
          echo "${{ github.run_number }}" >> versions.cfg
          newversion=$(cat versions.cfg)
          echo $newversion
          echo "::set-output name=versn::$newversion"
